apiVersion: apps/v1
kind: Deployment
metadata:
  name: <DEPLOY_NAME>-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: <APP_NAME>
  template:
    metadata:
      labels:
        app: <APP_NAME>
    spec:
      containers:
        - name: <APP_NAME>
          image: joeziet/server
          ports:
            - containerPort: 8081
