apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: <RS_NAME>-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: <APP_NAME>
  template:
    metadata:
      labels:
        app: <APP_NAME>
    spec:
      containers:
        - name: <APP_NAME>
          image: joeziet/server
          ports:
            - containerPort: 8081
